# golangci-lint configuration
version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - unused
    - gosec
    - unconvert
    - prealloc
    - modernize
    - gocritic
    - errorlint
    - nilerr
  disable:
    - funlen
    - gocognit
    - misspell
    - revive
  settings:
    gosec:
      excludes:
        - G204
        - G304
        - G301
        - G306
        - G122
        - G101
    modernize:
      enable-all: true
    gocritic:
      enable-all: true
      disabled-checks:
        - hugeParam
        - importShadow
        - paramTypeCombine
        - rangeValCopy
        - builtinShadow
        - builtinShadowDecl
        - ifElseChain
        - evalOrder
        - assignOp
        - unnamedResult
        - httpNoBody
        - octalLiteral
        - truncateCmp
        - unlambda
        - appendAssign
    errorlint:
      errorf: true
      asserts: true

issues:
  max-same-issues: 0